name: Deploy to Navel ERP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.NVERP_HOST }}
          username: ${{ secrets.NVERP_USER }}
          key: ${{ secrets.NVERP_KEY }}
          port: 22
          script: |
            echo "ðŸš€ Deploying to Navel server via SSH key..."
            cd /home/***/htdocs/navel.nexttechenterprise.site || exit
            git fetch origin
            git reset --hard origin/main
            rm -rf node_modules package-lock.json
            npm ci
            npm run build
pm2 startOrReload ecosystem.config.cjs
